config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts do
    resources :comments
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params.merge({'post_id':@post.id}))
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      @post = Post.find(params[:post_id])
      render :new
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:user_id,:description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice]= "Post Created Succesfully!"
      redirect_to posts_path
    else
      render :new
    end
  end
  def index
    @posts = Post.all
    # posts.each do |post|
    #   born = post.created_at
    #   now = Time.now
    #   age_s = now - born
    #   age_m = age_s/60
    #   rate = post.votes/age_m*0.1
    #   post.update(ranking:rate)
    # end
    # @posts = Post.all.order('id ASC').reorder('ranking DESC')
  end
  def show
    @post = Post.find(params[:id])
    @post.increment! :views
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice]= "Post Updated Succesfully!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice]= "Post Deleted Succesfully!"
    redirect_to posts_path
  end
  def rate
    @post = Post.find(params[:post])
    rating = params[:rating]
    count = @post.rating_count
    avg = @post.rating
    new_avg = ((count*avg)+rating)/(count+1)
    @post.increment! :rating_count
    @post.update(rating:new_avg)
    redirect_to post_path(@post)
  end

  private
  def post_params
    params.require(:post).permit(:user_id,:title,:image,:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice]= "User Created Succesfully!"
      redirect_to users_path
    else
      render :new
    end
  end
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]= "User Updated Succesfully!"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice]= "User Deleted Succesfully!"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name,:last_name,:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @comment %>


<%= form_for [@post,@comment] do |f| %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.select(:user_id) do %>
  <% User.all.each do |usr| %>
    <%= content_tag(:option, usr.username, value: usr.id) %>
  <% end %>
<% end %>
<%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing <%= @comment.description %></h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>Add a new comment to <%= @post.description%></h1>

<%= render 'form'%>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Behance</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo center">Logo</a>
          <ul class="left hide-on-med-and-down">
            <li>
              <a href="sass.html">Sass</a>
            </li>
            <li>
              <a href="badges.html">Components</a>
            </li>
            <li class="active">
              <a href="collapsible.html">JavaScript</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <div class="container">
      <blockquote >
        <%= flash[:notice] %>
        <%= flash[:alert] %>
      </blockquote>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>


<%= form_for @post do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :description %>
<%= f.text_field :description %>
<%= f.label :image %>
<%= f.text_field :image %>
<%= f.select(:user_id) do %>
  <% User.all.each do |usr| %>
    <%= content_tag(:option, usr.username, value: usr.id) %>
  <% end %>
<% end %>
<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post by <%= link_to @post.user.username, user_path(@post.user)%></h1>

<%= render 'form'%>

app/views/posts/index.html.erb
<h1>Behance</h1>
<% if @posts.any? %>
<ul>
  <% @posts.each do |post|%>
  <li>
   <%= link_to post.title, post_path(post) %> |
   by <%= link_to post.user.username, user_path(post.user) %> |
   Rating = <%= post.rating%> |
   Views = <%= post.views%> |
  </li>
<% end %>
</ul>
<%else%>
<h1>No posts yet</h1>
<%end%>

<hr>
<p><%= link_to "New Post", new_post_path%></p>
<p><%= link_to "New User", new_user_path%></p>

app/views/posts/new.html.erb
<h4>New Post</h4>

<%= render 'form'%>

app/views/posts/show.html.erb
<h1><%= @post.description%></h1>
Rating = <%= @post.rating%>
Views = <%= @post.views%>
<img src="<%= @post.image%>" alt="">
<% if @post.comments.any?%>
<ul>
<h4>Comments</h4>
<% @post.comments.each do |comment| %>
<li>
  <%=comment.description%> | by <%= link_to comment.user.username, user_path(comment.user)%>
<% end %>
</ul>
<% else %>
<h3>This Post has no comments yet!</h3>
<small>Post One Now!</small>
<% end %>
<p><%= link_to 'New Comment', new_post_comment_path(@post)%></p>

<hr>
<p><%= link_to 'Edit Post', edit_post_path(@post)%></p>
<p><%= link_to 'Delete Post', post_path(@post),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"}
                                         %></p>

app/views/users/_form.html.erb
<%= render 'layouts/errors', object:@user %>



<%= form_for @user do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name %>
<%= f.label :last_name %>
<%= f.text_field :last_name %>
<%= f.label :username %>
<%= f.text_field :username %>
<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h4>Editing <%=@user.username %>.</h4>

<%= render 'form'%>
<br>
<%= link_to 'Back', user_path(@user)%>

app/views/users/index.html.erb
<h1>Users</h1>

<% if @users.any? %>
<ul>
<% @users.each do |user| %>
<li>
  <p><%= link_to user.username, user_path(user) %></p>
</li>
<% end %>
</ul>
<% else %>
<h1>No users added yet!</h1>
<% end %>

<hr>
<p><%= link_to "New Post", new_post_path%></p>
<p><%= link_to "New User", new_user_path%>

app/views/users/new.html.erb
<h4>New User</h4>

<%= render 'form'%>

<%= link_to 'Back to All users', users_path %>

app/views/users/show.html.erb
<h1>Viewing <%= @user.username%></h1>

First name : <%= @user.first_name %>
Last name : <%= @user.last_name %>

<%= link_to 'Edit User', edit_user_path(@user)  %>
<%= link_to 'Delete User', user_path(@user),
                          :data => {:confirm => "Are you sure?",
                                         :method => "delete"}  %>